/**
 * iii Engine Config Generator
 *
 * Generates the iii-config.yaml that the engine process reads at startup.
 * Maps nvent module options to the iii engine config format.
 */

import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'
import { stringifyYAML } from 'confbox'

export interface IiiEngineConfig {
  /** WebSocket port for workers (default: 49134) */
  wsPort: number
  /** HTTP API port for registered endpoints (default: 3111) */
  httpPort: number
  /** WebSocket port for the Stream module (default: 3112) */
  streamPort: number
  /** Enable/disable optional modules */
  modules: {
    state: boolean
    queue: boolean
    cron: boolean
    observability: boolean
    stream: boolean
  }
}

/**
 * Generates the YAML string for iii-config.yaml from nvent config.
 */
export function generateIiiConfigYaml(cfg: IiiEngineConfig): string {
  const modules: object[] = [
    { class: 'modules::api::RestApiModule', config: { port: cfg.httpPort } },
  ]

  if (cfg.modules.state) modules.push({ class: 'modules::state::StateModule' })
  if (cfg.modules.queue) modules.push({ class: 'modules::queue::QueueModule' })
  if (cfg.modules.cron) modules.push({ class: 'modules::cron::CronModule' })
  if (cfg.modules.stream) modules.push({ class: 'modules::stream::StreamModule', config: { port: cfg.streamPort } })
  if (cfg.modules.observability) modules.push({ class: 'modules::observability::OtelModule' })

  return `# Auto-generated by nvent — do not edit manually\n` + stringifyYAML({ port: cfg.wsPort, modules })
}

/**
 * Writes the iii-config.yaml to the given path.
 */
export function writeIiiConfig(outputPath: string, cfg: IiiEngineConfig): void {
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, generateIiiConfigYaml(cfg), 'utf-8')
}

/**
 * Default config factory.
 */
export function defaultIiiEngineConfig(): IiiEngineConfig {
  return {
    wsPort: 49134,
    httpPort: 3111,
    streamPort: 3112,
    modules: {
      state: true,
      queue: true,
      cron: true,
      observability: true,
      stream: true,
    },
  }
}
