/**
 * iii Function Registry Scanner
 *
 * Scans server/functions/ directories at build time, derives function IDs
 * from file paths, and generates the iii-registry.mjs template that the
 * Nitro plugin imports at runtime.
 *
 * File path → function ID rules:
 *   server/functions/greet.ts           → 'greet'
 *   server/functions/orders/process.ts  → 'orders::process'
 *   server/functions/a/b/c.ts           → 'a::b::c'
 */

import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { globby } from 'globby'
import { genString } from 'knitwork'

export interface FunctionMeta {
  /** iii function ID (namespace::name) */
  id: string
  /** Absolute path to the source file */
  absPath: string
  /** Relative path used in the generated import */
  relativePath: string
  /** Optional human-readable description */
  description?: string
}

export interface PythonFunctionMeta {
  /** iii function ID (namespace::name) */
  id: string
  /** Absolute path to the .py source file */
  absPath: string
  /** Relative path within the functions dir */
  relativePath: string
  /**
   * When true, this function gets its own dedicated worker process.
   * Declare in the .py file: `meta = { ..., "standalone": True }`
   * Default: false (runs in the shared worker process)
   */
  standalone: boolean
}

export interface ScannedRegistry {
  functions: FunctionMeta[]
  pythonFunctions: PythonFunctionMeta[]
}

/**
 * Derives the iii function ID from a file path relative to the functions dir.
 * e.g. 'orders/process.ts' → 'orders::process'
 */
export function filePathToFunctionId(relPath: string): string {
  // Strip any file extension (.ts, .js, .py, etc.)
  const noExt = relPath.replace(/\.[a-zA-Z]+$/, '')
  return noExt.split(/[\\/]/).join('::')
}

/**
 * Reads a Python file and checks whether `meta` contains `"standalone": True`.
 * Intentionally a simple regex scan — no need to parse Python AST.
 */
function detectPythonStandalone(absPath: string): boolean {
  try {
    const src = readFileSync(absPath, 'utf-8')
    // Match:  "standalone": True  or  'standalone': True  (with optional spaces)
    return /['"]standalone['"]\s*:\s*True/.test(src)
  }
  catch {
    return false
  }
}

export interface ScanOptions {
  /** Array of layer info objects (rootDir + serverDir) */
  layerInfos: Array<{ rootDir: string; serverDir: string }>
  /** Functions directory relative to serverDir (default: 'functions') */
  functionsDir?: string
}

/**
 * Scans all configured function directories and returns metadata
 * for each discovered function file.
 */
export async function scanFunctions(opts: ScanOptions): Promise<ScannedRegistry> {
  const { layerInfos, functionsDir = 'functions' } = opts
  const functions: FunctionMeta[] = []
  const pythonFunctions: PythonFunctionMeta[] = []

  for (const layer of layerInfos) {
    const serverDir = layer.serverDir || join(layer.rootDir, 'server')
    const fnDir = join(serverDir, functionsDir)

    if (!existsSync(fnDir)) continue

    const [jsFiles, pyFiles] = await Promise.all([
      globby(['**/*.{ts,js,mts,mjs}'], {
        cwd: fnDir,
        absolute: false,
        ignore: ['**/*.d.ts', '**/*.test.*', '**/*.spec.*'],
      }),
      globby(['**/*.py'], {
        cwd: fnDir,
        absolute: false,
        ignore: ['**/__pycache__/**', '**/*.pyc'],
      }),
    ])

    for (const file of jsFiles) {
      functions.push({ id: filePathToFunctionId(file), absPath: join(fnDir, file), relativePath: file })
    }

    for (const file of pyFiles) {
      const absPath = join(fnDir, file)
      const standalone = detectPythonStandalone(absPath)
      pythonFunctions.push({ id: filePathToFunctionId(file), absPath, relativePath: file, standalone })
    }
  }

  return { functions, pythonFunctions }
}

/**
 * Generates the `.nuxt/iii-registry.mjs` template content.
 *
 * Supports both file conventions:
 *
 * **New style (`defineStep()`)** — default export is the step config object:
 *   `export default defineStep({ id, description, triggers, enqueues, flows, handler })`
 *
 * **Old style** — default export is the handler function, named exports for meta/triggers:
 *   `export default defineFunction(handler)`
 *   `export const meta = { id, description }`
 *   `export const triggers = [...]`
 *
 * A `_stepEntry` runtime normalizer in the generated file handles both transparently.
 */
export function generateIiiRegistryTemplate(scanned: ScannedRegistry): string {
  const lines: string[] = ['// auto-generated by nvent — do not edit', '']

  // Runtime normalizer: handles both defineStep() and legacy defineFunction() exports.
  // Takes the whole namespace object so Rollup can't statically trace member accesses
  // back to individual modules (avoids "not exported" warnings for defineStep files).
  lines.push(`function _stepEntry(ns, fallbackId, absPath) {`)
  lines.push(`  const def = ns.default`)
  lines.push(`  const meta = ns.meta`)
  lines.push(`  const triggers = ns.triggers`)
  lines.push(`  if (def?.__nventStep) {`)
  lines.push(`    const id = def.id ?? fallbackId`)
  lines.push(`    return { id, description: def.description, handler: def.handler, triggers: (def.triggers ?? []).map(t => ({ ...t, function_id: id })), enqueues: def.enqueues ?? [], flows: def.flows ?? [], stream: def.stream, filePath: absPath }`)
  lines.push(`  }`)
  lines.push(`  const id = meta?.id ?? fallbackId`)
  lines.push(`  return { id, description: meta?.description, handler: def, triggers: (triggers ?? []).map(t => ({ ...t, function_id: id })), enqueues: [], flows: [], stream: undefined, filePath: absPath }`)
  lines.push(`}`)
  lines.push('')

  const entries = scanned.functions.map((fn, i) => {
    const ns = `fn${i}`
    lines.push(`import * as ${ns} from ${genString(fn.absPath)}`)
    return `_stepEntry(${ns}, ${genString(fn.id)}, ${genString(fn.absPath)})`
  })

  lines.push('')
  lines.push(`export const registry = {`)
  lines.push(`  functions: [${entries.join(', ')}],`)
  lines.push(`  get triggers() { return this.functions.flatMap(f => f.triggers ?? []) },`)
  lines.push(`}`)
  lines.push('')
  lines.push('export default registry')
  lines.push('')
  lines.push(`export const pythonFunctions = ${JSON.stringify(scanned.pythonFunctions.map(fn => ({
    id: fn.id,
    absPath: fn.absPath,
    standalone: fn.standalone,
  })))}`)
  lines.push('')

  return lines.join('\n')
}


/**
 * Generates the entry script for a single standalone Python worker.
 *
 * The script imports shared logic from `_runtime.py` (which is copied to the
 * same `.nuxt/iii-workers/` directory at startup) and wires up one function.
 *
 * Generated output example:
 * ```python
 * # Auto-generated by nvent — do not edit
 * import sys, asyncio, os
 * sys.path.insert(0, os.path.dirname(__file__))
 * from _runtime import _iii_sdk, _load, _register
 *
 * async def main():
 *     client = _iii_sdk.III("ws://localhost:49134")
 *     mod = _load("/abs/path/to/fn.py", "fn::id")
 *     _register(client, mod, "fn::id")
 *     await client.connect()
 *     await asyncio.get_event_loop().create_future()
 *
 * if __name__ == "__main__":
 *     asyncio.run(main())
 * ```
 */
export function generatePythonWorkerScriptForFunction(fn: PythonFunctionMeta, wsUrl: string): string {
  return pythonEntryScript(wsUrl, [fn])
}

/**
 * Generates the shared worker entry script that registers ALL non-standalone
 * Python functions in a single process. This is the default mode.
 */
export function generatePythonWorkerScriptForAll(fns: PythonFunctionMeta[], wsUrl: string): string {
  return pythonEntryScript(wsUrl, fns)
}

/**
 * Builds a minimal Python entry script that:
 *   1. Puts its own directory on sys.path so `_runtime` can be imported
 *   2. Imports shared helpers from `_runtime.py`
 *   3. Loads and registers each function
 *   4. Connects and keeps alive
 */
function pythonEntryScript(wsUrl: string, fns: PythonFunctionMeta[]): string {
  const lines = [
    '# Auto-generated by nvent — do not edit',
    'import sys, asyncio, os',
    'sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))',
    'from _runtime import _iii_sdk, _load, _register',
    '',
    '',
    'async def main():',
    `    client = _iii_sdk.III(${JSON.stringify(wsUrl)})`,
  ]

  for (const fn of fns) {
    lines.push(`    mod = _load(${JSON.stringify(fn.absPath)}, ${JSON.stringify(fn.id)})`)
    lines.push(`    _register(client, mod, ${JSON.stringify(fn.id)})`)
  }

  lines.push(
    '    await client.connect()',
    '    await asyncio.get_event_loop().create_future()  # keep alive until killed',
    '',
    '',
    'if __name__ == "__main__":',
    '    asyncio.run(main())',
    '',
  )

  return lines.join('\n')
}

